<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasTable('slip_templates')) {
            return;
        }

        Schema::table('slip_templates', function (Blueprint $table) {
            if (!Schema::hasColumn('slip_templates', 'schedule_title')) {
                $table->string('schedule_title', 150)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'title')) {
                $table->string('title', 150)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'clause_title')) {
                $table->string('clause_title', 150)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'description')) {
                $table->string('description', 255)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'wording')) {
                $table->text('wording')->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'class_group_code')) {
                $table->string('class_group_code', 20)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'class_code')) {
                $table->string('class_code', 20)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'class_group')) {
                $table->string('class_group', 100)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'class_name')) {
                $table->string('class_name', 120)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'status')) {
                $table->char('status', 1)->default('A');
            }
            if (!Schema::hasColumn('slip_templates', 'type_of_bus')) {
                $table->string('type_of_bus', 20)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'treaty_type')) {
                $table->string('treaty_type', 20)->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'created_by')) {
                $table->string('created_by', 100)->default('system');
            }
            if (!Schema::hasColumn('slip_templates', 'updated_by')) {
                $table->string('updated_by', 100)->default('system');
            }
            if (!Schema::hasColumn('slip_templates', 'created_at')) {
                $table->timestamp('created_at')->nullable();
            }
            if (!Schema::hasColumn('slip_templates', 'updated_at')) {
                $table->timestamp('updated_at')->nullable();
            }
        });

        // Backfill title fields so UI/controller can read/write consistently.
        DB::statement("
            UPDATE slip_templates
            SET schedule_title = COALESCE(schedule_title, title, clause_title),
                title = COALESCE(title, schedule_title, clause_title),
                clause_title = COALESCE(clause_title, schedule_title, title)
        ");

        // Keep description populated where possible.
        DB::statement("
            UPDATE slip_templates
            SET description = COALESCE(description, LEFT(COALESCE(wording, ''), 255))
            WHERE description IS NULL
        ");

        // Enforce safe defaults for audit columns.
        DB::statement("UPDATE slip_templates SET created_by = 'system' WHERE created_by IS NULL OR created_by = ''");
        DB::statement("UPDATE slip_templates SET updated_by = 'system' WHERE updated_by IS NULL OR updated_by = ''");

        $driver = DB::getDriverName();
        if ($driver === 'pgsql') {
            DB::statement("ALTER TABLE slip_templates ALTER COLUMN created_by SET DEFAULT 'system'");
            DB::statement("ALTER TABLE slip_templates ALTER COLUMN updated_by SET DEFAULT 'system'");

            // Add id identity column when missing and backfill existing rows.
            if (!Schema::hasColumn('slip_templates', 'id')) {
                DB::statement("ALTER TABLE slip_templates ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY");
                DB::statement("UPDATE slip_templates SET id = DEFAULT WHERE id IS NULL");
                DB::statement("ALTER TABLE slip_templates ALTER COLUMN id SET NOT NULL");

                $hasPrimaryKey = DB::selectOne("
                    SELECT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'slip_templates'::regclass
                          AND contype = 'p'
                    ) AS has_pk
                ");

                if (!($hasPrimaryKey->has_pk ?? false)) {
                    DB::statement("ALTER TABLE slip_templates ADD CONSTRAINT slip_templates_pkey PRIMARY KEY (id)");
                } else {
                    DB::statement("CREATE UNIQUE INDEX IF NOT EXISTS slip_templates_id_unique ON slip_templates(id)");
                }
            }
        } elseif ($driver === 'mysql') {
            DB::statement("ALTER TABLE slip_templates MODIFY created_by VARCHAR(100) NOT NULL DEFAULT 'system'");
            DB::statement("ALTER TABLE slip_templates MODIFY updated_by VARCHAR(100) NOT NULL DEFAULT 'system'");

            if (!Schema::hasColumn('slip_templates', 'id')) {
                DB::statement("ALTER TABLE slip_templates ADD COLUMN id BIGINT UNSIGNED NULL");
                DB::statement("SET @rownum := 0");
                DB::statement("UPDATE slip_templates SET id = (@rownum := @rownum + 1) WHERE id IS NULL");
                DB::statement("ALTER TABLE slip_templates MODIFY id BIGINT UNSIGNED NOT NULL");
                DB::statement("ALTER TABLE slip_templates ADD UNIQUE INDEX slip_templates_id_unique (id)");
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Intentionally left non-destructive to avoid dropping live columns/data.
    }
};

